server:
    port: 8081

spring:
    main:
        web-application-type: servlet
        
    profiles:
        active: dev
    
    application:
        name: microservice-2
    
    config:
        import:
            - security/application-db.yml

kafka:
  bootstrap:
    servers: localhost:9092
